<?php

namespace eazy\http\di;

use eazy\base\BaseObject;
use eazy\http\App;
use eazy\http\exceptions\InvalidConfigException;
use eazy\http\Request;
use Psr\Container\ContainerInterface;

/**
 * Simple container.
 */
class Container extends BaseObject implements ContainerInterface
{
    /**
     * @var \eazy\http\di\Container
     */
    public static $instance;
    
    /**
     * Singleton objects.
     * @var array
     */
    private array $_singletons = [];

    /**
     * Init container instance.
     */
    protected function init()
    {
        self::$instance = $this;
        parent::init(); // TODO: Change the autogenerated stub
    }
    
    /**
     * Set container singleton.
     * ```php
     * // set class based on string definition and array params.
     * Container::set('classname', [
     *      'foo' => 'bar',
     * ]);
     * ```
     * @param string $name
     * @param  array  $params
     *
     * @return $this
     * @throws \eazy\http\exceptions\InvalidConfigException
     */
    public function set(string $name, array $params = [])
    {
        $definition = $this->normalizeDefinition($name, $params);
        $this->_singletons[$name] = $this->build($definition, $params);
    }

    /**
     * Get singleton.
     * @param  string  $class
     * @param  array  $params
     * @param  array  $config
     *
     * @return \eazy\http\Request
     */
    public function get($class, $params = [], $config = [])
    {
        if (isset($this->_singletons[$class])) {
            return $this->_singletons[$class];
        }

        // use context singletons.
        //throw new InvalidConfigException('Failed to get component $class');
    }

    /**
     * Build object.
     * @param $class
     * @param $params
     *
     * @return object|void
     * @throws \ReflectionException
     */
    public function build($definition)
    {
        return $this->makeObject($definition);
    }

    protected function makeObject($definition)
    {
        $ref = new \ReflectionClass($definition['class']);
        unset($definition['class']);
        return $ref->newInstanceArgs([$definition]);
    }

    /**
     * Normalize definition.
     * It will merge definition and params using for build object.
     * @param $class
     * @param $definition
     *
     * @return array|void
     * @throws \eazy\http\exceptions\InvalidConfigException
     */
    public function normalizeDefinition($definition, $params)
    {
        if (is_string($definition)) {
            return array_merge(['class' => $definition], $params);
        }

        throw new InvalidConfigException("Unsupported definition type for \"$class\": " . gettype($definition));
    }

    public function has(string $id)
    {
        if (isset($this->_singletons[$id])) {
            return true;
        }

        return false;
    }
}