<?php

namespace eazy\http;

class BaseAttributes extends BaseObject
{
    public static $instance;
    
    private $_attributesMap;
    
    public function init()
    {
        self::$instance = $this;
        parent::init(); // TODO: Change the autogenerated stub
    }
    
    abstract public function getAttrubutes();

    abstract public function getAttrubute();
}