<?php

namespace eazy\http;

class BaseHook extends ContextComponent
{
    public function init()
    {
        $refClass = new \ReflectionClass($this);
        foreach ($refClass->getMethods() as $method) {
            $attributes = $method->getAttributes(Hook::class);
            foreach ($attributes as $attribute) {
                foreach ($attribute->getArguments() as $argument) {
                    $f = $method->getName();
                    Hook::bind($argument , function() use ($f) {
                        call_user_func([$this, $f]);
                    });
                }
            }
        }
//        $classAttrs = $refClass->getAttributes(Hook::class);
        
        parent::init(); // TODO: Change the autogenerated stub
    }
}