<?php

namespace eazy\http;

class PDOConnection extends Component
{
    public $pools;

    public function init()
    {
        var_dump(get_called_class());
        parent::init(); // TODO: Change the autogenerated stub
    }
}