<?php

namespace eazy\http\databases;

use eazy\http\PDOConnection;

/**
 * ->withHost('192.168.10.139')
->withPort(3306)
// ->withUnixSocket('/tmp/mysql.sock')
->withDbName('mjb')
->withCharset('utf8mb4')
->withUsername('root')
->withPassword('root')
 */
class DbConnection extends PDOConnection
{
    public $host;
    public $dbname;
    public $charset;
    public $username;
    public $password;

    public $connection;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}