<?php

namespace eazy\http\databases;

use eazy\http\PDOConnection;
use Swoole\Database\PDOConfig;
use Swoole\Database\PDOPool;

/**
 * ->withHost('192.168.10.139')
->withPort(3306)
// ->withUnixSocket('/tmp/mysql.sock')
->withDbName('mjb')
->withCharset('utf8mb4')
->withUsername('root')
->withPassword('root')
 */
class DbConnection extends PDOConnection
{
    public $host;
    public $port;
    public $dbname;
    public $charset;
    public $username;
    public $password;
    public $poolsize;

    /**
     * @var PDOPool
     */
    protected $pool;

    public function init()
    {
        $this->pool = new PDOPool((new PDOConfig())
            ->withHost($this->host)
            ->withPort($this->port)
            // ->withUnixSocket('/tmp/mysql.sock')
            ->withDbName($this->dbname)
            ->withCharset($this->charset)
            ->withUsername($this->username)
            ->withPassword($this->password)
            , 1024);

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function getConnection()
    {
        $this->pool->get();
    }

    public function close($connection = null)
    {
        $this->pool->put($connection);
    }

    
}